RABBITMQ_CONSUMER_INSTANCES: '1'
DEFAULT_MAP_TYPE: 'roadmap'
LANG: 'en_US.UTF-8'
RAILS_SERVE_STATIC_FILES: 'enabled'
RABBITMQ_PASSWORD_MESSAGES_CHANNEL: 'messages'
EXCEPTION_NOTIFIER_RECIPIENTS: 'mario.souto@moove-it.com matias.garcia@moove-it.com virginia.rodriguez@moove-it.com daniel.porzio@moove-it.com'

development:
  QIOT_IO_API_TOKEN: ''
  GOOGLE_MAPS_API_KEY: ''
  RABBITMQ_HOST: '127.0.0.1'
  RABBITMQ_PORT: '5672'
  RABBITMQ_USER: 'admin'
  RABBITMQ_PASSWORD: 'admin'



  QIOT_USER_SERVICE_URL: 'http://localhost:3001'
  QIOT_ACCOUNT_TOKEN_IDENTIFIER: ''
  QIOT_ACCOUNT_TOKEN: ''
  RABBITMQ_PASSWORD_MESSAGES_CHANNEL: 'messages_rami'


  
# development:
#   QIOT_IO_API_TOKEN: ''
#   GOOGLE_MAPS_API_KEY: ''
#   
#   QIOT_USER_SERVICE_URL: 'http://qiot.io'
#   QIOT_ACCOUNT_TOKEN_IDENTIFIER: ''
#   QIOT_ACCOUNT_TOKEN: ''
#   RABBITMQ_PASSWORD_MESSAGES_CHANNEL: 'messages'  

production:
  RACK_ENV: 'production'
  RAILS_ENV: 'production'
  SECRET_KEY_BASE: ''
  SMTP_PASSWORD: ''
  

# dev:
#   CLOUDAMQP_URL: ''
#   DATABASE_URL: ''
#   GOOGLE_MAPS_API_KEY: ''
#   QIOT_ACCOUNT_TOKEN: ''
#   QIOT_ACCOUNT_TOKEN_IDENTIFIER: ''
#   QIOT_IO_API_TOKEN: ''
#   QIOT_USER_SERVICE_URL: ''
#   RACK_ENV: 'dev'
#   RAILS_ENV: 'dev'
#   SECRET_KEY_BASE: ''
#   SMTP_PASSWORD: ''

# stg:
#   CLOUDAMQP_URL: ''
#   DATABASE_URL: ''
#   GOOGLE_MAPS_API_KEY: ''
#   QIOT_ACCOUNT_TOKEN: ''
#   QIOT_ACCOUNT_TOKEN_IDENTIFIER: ''
#   QIOT_IO_API_TOKEN: ''
#   QIOT_USER_SERVICE_URL: ''
#   RACK_ENV: 'staging'
#   RAILS_ENV: 'staging'
#   SECRET_KEY_BASE: ''
#   SMTP_PASSWORD: ''

# prd:
#   CLOUDAMQP_URL: ''
#   DATABASE_URL: ''
#   DEFAULT_MAP_TYPE:
#   GOOGLE_MAPS_API_KEY: ''
#   QIOT_ACCOUNT_TOKEN: ''
#   QIOT_ACCOUNT_TOKEN_IDENTIFIER: ''
#   QIOT_IO_API_TOKEN: ''
#   QIOT_USER_SERVICE_URL: ''
#   RACK_ENV: 'production'
#   RAILS_ENV: 'production'
  # SECRET_KEY_BASE: ''
#   SMTP_PASSWORD: ''
