RABBITMQ_CONSUMER_INSTANCES: '1'
DEFAULT_MAP_TYPE: 'roadmap'
LANG: 'en_US.UTF-8'
RAILS_SERVE_STATIC_FILES: 'enabled'
RABBITMQ_PASSWORD_MESSAGES_CHANNEL: 'messages'
EXCEPTION_NOTIFIER_RECIPIENTS: 'mario.souto@moove-it.com matias.garcia@moove-it.com virginia.rodriguez@moove-it.com daniel.porzio@moove-it.com'

development:
  QIOT_IO_API_TOKEN: ''
  GOOGLE_MAPS_API_KEY: ''
  RABBITMQ_HOST: '127.0.0.1'
  RABBITMQ_PORT: '5672'
  RABBITMQ_USER: 'admin'
  RABBITMQ_PASSWORD: 'admin'
  QIOT_USER_SERVICE_URL: 'http://localhost:3001'
  QIOT_ACCOUNT_TOKEN_IDENTIFIER: ''
  QIOT_ACCOUNT_TOKEN: ''
  RABBITMQ_PASSWORD_MESSAGES_CHANNEL: 'messages_rami'

  # SMTP_DOMAIN: 'byteforza.com'
  # SMTP_HOST: 'smtp.office365.com' 
  # SMTP_PASSWORD: 'Ramibe$26' 
  # SMTP_PORT: '587' 
  # SMTP_USERNAME: 'ramesh.k@byteforza.com'

  # SMTP_DOMAIN: 'sendgrid.net'
  # SMTP_HOST: 'smtp.sendgrid.net' 
  # SMTP_PASSWORD: 'Ramibe$26' 
  # SMTP_PORT: '587' 
  # SMTP_USERNAME: 'ramisn'

  # SMTP_DOMAIN: 'gmail.com'
  # SMTP_ADDR: 'smtp.gmail.com' 
  # SMTP_PASSWORD: 'ramibe36'
  # SMTP_PORT: '587' 
  # SMTP_USERNAME: 'rameshkror'

  # cmFtaXNuCg==
  # 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


  SMTP_DOMAIN: 'gmail.com'
  SMTP_HOST: 'smtp.gmail.com' 
  SMTP_PASSWORD: 'ramibe36' 
  SMTP_PORT: '587' 
  SMTP_USERNAME: 'rameshkror'

  MAILGUN_SMTP_PORT: '587'
  MAILGUN_SMTP_SERVER: 'smtp.mailgun.org'
  MAILGUN_SMTP_LOGIN: 'postmaster@sandbox3845405bcd6d455d96b827b011bd3cb4.mailgun.org'
  MAILGUN_SMTP_PASSWORD: '803e97cc5700068d0ba740133a062576-8b34de1b-e47754b4'

# Mandril
# username: ramisn
# pwd: 77bdee6acc0916232dfc9d2873882096-us16



# "smtpOptions": {

#         "host": "smtp.ethereal.email",

#     "port": 587,

#     "auth": {

#         "user": "augustus.kohler@ethereal.email",

#         "pass": "g9kBubGAx3dPq2ptUK"

#         }
  # SMTP_DOMAIN: 'byteforza.com'
  # SMTP_HOST: 'smtp.office365.com' 
  # SMTP_PASSWORD: 'Ramibe$26' 
  # SMTP_PORT: '587' 
  # SMTP_USERNAME: 'ramesh.k@byteforza.com'

# development:
#   QIOT_IO_API_TOKEN: ''
#   GOOGLE_MAPS_API_KEY: ''
#   RABBITMQ_HOST: 'https://devoted-collie.rmq.cloudamqp.com/'
#   RABBITMQ_PORT: '5672'
#   RABBITMQ_USER: 'sfmysjdr'
#   RABBITMQ_PASSWORD: 'MWafevjRVSzWJXfWoq5J4SbKXEoxQqoX'
#   QIOT_USER_SERVICE_URL: 'http://qiot.io'
#   QIOT_ACCOUNT_TOKEN_IDENTIFIER: ''
#   QIOT_ACCOUNT_TOKEN: ''
#   RABBITMQ_PASSWORD_MESSAGES_CHANNEL: 'messages'  

# development:
#   QIOT_IO_API_TOKEN: ''
#   GOOGLE_MAPS_API_KEY: ''
#   RABBITMQ_HOST: 'mqtt.flespi.io'
#   RABBITMQ_PORT: '1883'
#   RABBITMQ_USER: 'LwPT1Kg3H6egbaUCM60vwR0OqCcFxeC9yfSpOYilVlrUj9lW3bhoQ626w2AU42Ts'
#   RABBITMQ_PASSWORD: ''
#   QIOT_USER_SERVICE_URL: ''
#   QIOT_ACCOUNT_TOKEN_IDENTIFIER: ''
#   QIOT_ACCOUNT_TOKEN: ''
#   RABBITMQ_PASSWORD_MESSAGES_CHANNEL: 'messages_mqtt' 

production:
  # SMTP_DOMAIN: 'gmail.com'
  # SMTP_HOST: 'smtp.gmail.com' 
  # SMTP_PASSWORD: 'ramibe36' 
  # SMTP_PORT: '587' 
  # SMTP_USERNAME: 'rameshkror'
  # ENV['SMTP_ADDR']

  # SMTP_DOMAIN: 'heroku.com'
  # SMTP_HOST: 'smtp.sendgrid.net' 
  # SMTP_PASSWORD: 'Ramibe$26' 
  # SMTP_PORT: '587' 
  # SMTP_USERNAME: 'ramisn'

  SMTP_DOMAIN: 'heroku.com'
  SMTP_HOST: 'smtp.ethereal.email' 
  SMTP_PASSWORD: 'g9kBubGAx3dPq2ptUK' 
  SMTP_PORT: '587' 
  SMTP_USERNAME: 'augustus.kohler@ethereal.email'

  MAILGUN_SMTP_PORT: '587'
  MAILGUN_SMTP_SERVER: 'smtp.mailgun.org'
  MAILGUN_SMTP_LOGIN: 'postmaster@sandbox3845405bcd6d455d96b827b011bd3cb4.mailgun.org'
  MAILGUN_SMTP_PASSWORD: '803e97cc5700068d0ba740133a062576-8b34de1b-e47754b4'

  # SMTP_DOMAIN: 'heroku.com'
  # SMTP_HOST: 'smtp.office365.com' 
  # SMTP_PASSWORD: 'Ramibe$26' 
  # SMTP_PORT: '587' 
  # SMTP_USERNAME: 'ramesh.k@byteforza.com'

  # SMTP_DOMAIN: 'byteforza.com'
  # SMTP_HOST: 'smtp.office365.com' 
  # SMTP_PASSWORD: 'Ramibe$26' 
  # SMTP_PORT: '587' 
  # SMTP_USERNAME: 'ramesh.k@byteforza.com'

# dev:
#   CLOUDAMQP_URL: ''
#   DATABASE_URL: ''
#   GOOGLE_MAPS_API_KEY: ''
#   QIOT_ACCOUNT_TOKEN: ''
#   QIOT_ACCOUNT_TOKEN_IDENTIFIER: ''
#   QIOT_IO_API_TOKEN: ''
#   QIOT_USER_SERVICE_URL: ''
#   RACK_ENV: 'dev'
#   RAILS_ENV: 'dev'
#   SECRET_KEY_BASE: ''
#   SMTP_PASSWORD: ''

# stg:
#   CLOUDAMQP_URL: ''
#   DATABASE_URL: ''
#   GOOGLE_MAPS_API_KEY: ''
#   QIOT_ACCOUNT_TOKEN: ''
#   QIOT_ACCOUNT_TOKEN_IDENTIFIER: ''
#   QIOT_IO_API_TOKEN: ''
#   QIOT_USER_SERVICE_URL: ''
#   RACK_ENV: 'staging'
#   RAILS_ENV: 'staging'
#   SECRET_KEY_BASE: ''
#   SMTP_PASSWORD: ''

# prd:
#   CLOUDAMQP_URL: ''
#   DATABASE_URL: ''
#   DEFAULT_MAP_TYPE:
#   GOOGLE_MAPS_API_KEY: ''
#   QIOT_ACCOUNT_TOKEN: ''
#   QIOT_ACCOUNT_TOKEN_IDENTIFIER: ''
#   QIOT_IO_API_TOKEN: ''
#   QIOT_USER_SERVICE_URL: ''
#   RACK_ENV: 'production'
#   RAILS_ENV: 'production'
#   SECRET_KEY_BASE: ''
#   SMTP_PASSWORD: ''
